const fs = require("fs");
const path = require("path");

const PLUGIN_NAME = "CanopyTailwindCandidatesPlugin";
const CACHE_DIR = "node_modules/.cache/canopy-tailwind";
// Deliberately not `.css`. Every repo has a `{ test: /\.css$/, include: [node_modules] }`
// rule, and webpack applies every matching rule, so a generated `.css` in here would pick
// up a second loader chain alongside ours and ship unprocessed Tailwind directives.
const ENTRY_FILE = "entry.tailwind";
const CANDIDATES_FILE = "candidates";
const BASE_CSS = path.resolve(__dirname, "base.css");

// tailwindcss is our dependency, not the consuming repo's, so the entry cannot reach it
// with a bare specifier — the entry resolves from the repo's node_modules, where it may
// not be hoisted. An absolute path produces byte-identical output and always resolves.
const TAILWIND_CSS_DIR = path.dirname(
  require.resolve("tailwindcss/package.json"),
);

// What a consumer writes in their app entry. Aliased to the generated file below.
const PUBLIC_SPECIFIER = "canopy-webpack-config/tailwind.css";

const DEFAULT_SOURCES = ["src/**/*.{js,jsx,ts,tsx}"];

// Tailwind's built-in prefix only generates a utility when the prefixed candidate
// appears literally in a scanned file. Our tw() helper composes the prefix at runtime,
// so the scanner never sees it. We run Tailwind's own extractor ourselves, prepend the
// prefix to everything it finds, and hand the result back through @source.
//
// oxide is a native binary pinned to an exact version by @tailwindcss/postcss, and the
// extraction has to match the Tailwind that actually builds the CSS. Both are our
// dependencies now, so resolving from here is what guarantees they agree.
function loadScanner() {
  try {
    return require("@tailwindcss/oxide").Scanner;
  } catch (err) {
    throw new Error(
      `${PLUGIN_NAME}: could not load @tailwindcss/oxide. It ships with our own ` +
        `@tailwindcss/postcss, so this is a broken canopy-webpack-config install — on ` +
        `CI more often a missing platform binary than a missing package; see the cause.`,
      { cause: err },
    );
  }
}

function buildEntry(prefix, extendPath) {
  let base;
  try {
    base = fs.readFileSync(BASE_CSS, "utf8");
  } catch (err) {
    throw new Error(
      `${PLUGIN_NAME}: could not read the shared Tailwind base at ${BASE_CSS}. This is ` +
        `a broken canopy-webpack-config install, not a problem with your repo.`,
      { cause: err },
    );
  }

  return [
    `/* Generated by canopy-webpack-config on every build — edits here are lost.`,
    ` * Change the \`tailwind\` option in your webpack config, or src/tailwind/base.css`,
    ` * in canopy-webpack-config for boilerplate every app shares. */`,
    ``,
    `@import "${TAILWIND_CSS_DIR}/theme.css" prefix(${prefix});`,
    `@import "${TAILWIND_CSS_DIR}/utilities.css" prefix(${prefix});`,
    ``,
    base.trim(),
    ``,
    // Absolute so it does not depend on where the repo-specific file sits.
    ...(extendPath ? [`@import "${extendPath}";`, ``] : []),
    `@source "./${CANDIDATES_FILE}";`,
    ``,
  ].join("\n");
}

class TailwindCandidatesPlugin {
  constructor(options = {}) {
    const {
      prefix,
      context = process.cwd(),
      sources = DEFAULT_SOURCES,
      extend,
    } = options;

    if (typeof prefix !== "string" || !prefix) {
      throw new Error(
        `${PLUGIN_NAME}: \`prefix\` is required, e.g. { prefix: "ru" }`,
      );
    }

    this.prefix = prefix;
    this.context = context;
    this.sources = sources;
    this.extendPath = extend ? path.resolve(context, extend) : null;
    this.cacheDir = path.resolve(context, CACHE_DIR);
    this.entryPath = path.join(this.cacheDir, ENTRY_FILE);
    this.candidatesPath = path.join(this.cacheDir, CANDIDATES_FILE);
  }

  // Rewriting an unchanged file would invalidate the Tailwind entry on every compile and
  // loop the dev server.
  writeIfChanged(filePath, contents) {
    let previous;
    try {
      previous = fs.readFileSync(filePath, "utf8");
    } catch (err) {
      if (err && err.code === "ENOENT") {
        previous = null;
      } else {
        throw err;
      }
    }

    if (previous === contents) return false;

    fs.mkdirSync(path.dirname(filePath), { recursive: true });
    fs.writeFileSync(filePath, contents);
    return true;
  }

  generate() {
    if (this.extendPath && !fs.existsSync(this.extendPath)) {
      throw new Error(
        `${PLUGIN_NAME}: \`tailwind.extend\` points at ${this.extendPath}, which does ` +
          `not exist.`,
      );
    }

    const Scanner = loadScanner();
    const scanner = new Scanner({
      sources: this.sources.map((pattern) => ({
        base: this.context,
        pattern,
        negated: false,
      })),
    });

    const candidates = scanner.scan();

    if (candidates.length === 0) {
      throw new Error(
        `${PLUGIN_NAME}: found no Tailwind candidates under ${this.sources.join(", ")}. ` +
          `Building it would produce an empty stylesheet.`,
      );
    }

    // Everything the extractor found gets the prefix
    const contents =
      candidates.map((c) => `${this.prefix}:${c}`).join("\n") + "\n";

    const changed = this.writeIfChanged(this.candidatesPath, contents);
    this.writeIfChanged(
      this.entryPath,
      buildEntry(this.prefix, this.extendPath),
    );

    return { count: candidates.length, files: scanner.files, changed };
  }

  apply(compiler) {
    // beforeCompile lands before any module is resolved or built, so both generated
    // files are on disk by the time webpack resolves the alias and postcss-loader reads the entry
    compiler.hooks.beforeCompile.tap(PLUGIN_NAME, () => {
      this.lastError = null;
      try {
        this.lastRun = this.generate();
      } catch (err) {
        this.lastError = err;
        if (!compiler.watchMode) throw err;
      }
    });

    compiler.hooks.afterCompile.tap(PLUGIN_NAME, (compilation) => {
      if (this.lastError) {
        compilation.errors.push(this.lastError);
        return;
      }

      const run = this.lastRun;
      if (!run) return;

      // @tailwindcss/postcss reports the candidates file as a dependency and
      // postcss-loader forwards it, so edits to a file already in the graph rebuild on
      // their own. Registering the scanned files and their roots covers additions and
      // deletions.
      for (const file of run.files) {
        compilation.fileDependencies.add(file);
      }
      for (const pattern of this.sources) {
        compilation.contextDependencies.add(
          path.resolve(this.context, pattern.split("*")[0]),
        );
      }
      if (this.extendPath) {
        compilation.fileDependencies.add(this.extendPath);
      }

      compilation
        .getLogger(PLUGIN_NAME)
        .info(
          `${run.changed ? "wrote" : "reused"} ${run.count} prefixed candidates ` +
            `(${this.prefix}:) from ${run.files.length} files`,
        );
    });
  }
}

function tailwindRule(entryPath) {
  return {
    test: (resource) => resource === entryPath,
    use: [
      { loader: require.resolve("style-loader") },
      { loader: require.resolve("css-loader") },
      {
        loader: require.resolve("postcss-loader"),
        options: {
          postcssOptions: { plugins: [require("@tailwindcss/postcss")] },
        },
      },
    ],
  };
}

// Returns the rule, plugin and alias a consuming config needs, or empty ones when the
// repo has not opted in.
function tailwindSupport(tailwind) {
  if (!tailwind) {
    return { rules: [], plugins: [], alias: {} };
  }

  const plugin = new TailwindCandidatesPlugin(tailwind);

  return {
    rules: [tailwindRule(plugin.entryPath)],
    plugins: [plugin],
    // `$` makes this an exact match, so it only ever catches the stylesheet import.
    alias: { [`${PUBLIC_SPECIFIER}$`]: plugin.entryPath },
  };
}

module.exports = {
  TailwindCandidatesPlugin,
  tailwindRule,
  tailwindSupport,
  buildEntry,
  BASE_CSS,
  CACHE_DIR,
  ENTRY_FILE,
  CANDIDATES_FILE,
  PUBLIC_SPECIFIER,
};
